// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/golang/mock/gomock"
	"github.com/google/wire"
	"github.com/zillow/howegoatzillow/libs/config"
	"github.com/zillow/howegoatzillow/libs/db"
	"github.com/zillow/howegoatzillow/libs/http"
	"github.com/zillow/howegoatzillow/libs/kafka"
	"github.com/zillow/howegoatzillow/libs/logger"
	"github.com/zillow/howegoatzillow/libs/server"
	"github.com/zillow/howegoatzillow/mocks/db"
	"github.com/zillow/howegoatzillow/mocks/kafka"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, func()) {
	appConfig := config.NewAppConfig()
	serverConfig := NewServerConfig(appConfig)
	tracer := NewTracer()
	loggerLogger, cleanup := logger.NewLogger(tracer)
	factory := NewServerFactory(serverConfig, loggerLogger, tracer)
	httpConfig := NewHttpServiceConfig(appConfig)
	leveledLogger := http.NewLeveledLogger(loggerLogger)
	provider := http.NewClientProvider(tracer, leveledLogger)
	dbConfig := NewDbConfig(appConfig)
	dbProvider := db.NewProvider()
	kafkaConfig := NewKafkaConfig(appConfig)
	client := kafka.NewClient(kafkaConfig, tracer, loggerLogger)
	myService := MyService{
		ServerFactory:      factory,
		HTTPConfig:         httpConfig,
		HTTPClientProvider: provider,
		DBConfig:           dbConfig,
		DBProvider:         dbProvider,
		KafkaConfig:        kafkaConfig,
		KafkaClient:        client,
	}
	serverServer := NewServer(myService)
	return serverServer, func() {
		cleanup()
	}
}

func InitializeServerTestable(ctrl *gomock.Controller) (*ServerTestable, func()) {
	appConfig := config.NewAppConfig()
	serverConfig := NewServerConfig(appConfig)
	tracer := NewTracer()
	loggerLogger, cleanup := logger.NewLogger(tracer)
	factory := NewServerFactory(serverConfig, loggerLogger, tracer)
	httpConfig := NewHttpServiceConfig(appConfig)
	leveledLogger := http.NewLeveledLogger(loggerLogger)
	provider := http.NewClientProvider(tracer, leveledLogger)
	dbConfig := NewDbConfig(appConfig)
	mockProvider := mock_db.NewMockProvider(ctrl)
	kafkaConfig := NewKafkaConfig(appConfig)
	mockClient := mock_kafka.NewMockClient(ctrl)
	myService := MyService{
		ServerFactory:      factory,
		HTTPConfig:         httpConfig,
		HTTPClientProvider: provider,
		DBConfig:           dbConfig,
		DBProvider:         mockProvider,
		KafkaConfig:        kafkaConfig,
		KafkaClient:        mockClient,
	}
	serverServer := NewServer(myService)
	mockWriter := mock_kafka.NewMockWriter(ctrl)
	serverTestable := &ServerTestable{
		Server:     serverServer,
		DBProvider: mockProvider,
		KProvider:  mockClient,
		KWriter:    mockWriter,
	}
	return serverTestable, func() {
		cleanup()
	}
}

// wire.go:

// This is in a separate common package
var ZCommonSet = wire.NewSet(
	NewServerConfig,
	NewServerFactory, config.NewAppConfig, NewKafkaConfig, kafka.NewClient, wire.Bind(new(kafka.Logger), new(logger.Logger)), logger.NewLogger, NewTracer,
	NewDbConfig, db.NewProvider, NewHttpServiceConfig, http.NewClientProvider, wire.Bind(new(http.Logger), new(logger.Logger)), http.NewLeveledLogger,
)

var ZCommonMockSet = wire.NewSet(
	NewServerConfig,
	NewServerFactory, config.NewAppConfig, NewKafkaConfig, logger.NewLogger, NewTracer,
	NewDbConfig,
	NewHttpServiceConfig, http.NewClientProvider, wire.Bind(new(http.Logger), new(logger.Logger)), http.NewLeveledLogger, mock_kafka.NewMockClient, mock_kafka.NewMockWriter, mock_db.NewMockProvider, wire.Bind(new(db.Provider), new(*mock_db.MockProvider)), wire.Bind(new(kafka.Client), new(*mock_kafka.MockClient)),
)
